# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # - id: check-yaml
      - id: check-added-large-files
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang.
      - id: check-shebang-scripts-are-executable # ensures that (non-binary) files with a shebang are executable.

  # Shellcheck
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  # Dockerfile linter
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint

  #- repo: https://github.com/pre-commit/mirrors-prettier
    #  rev: v4.0.0-alpha.8
    #hooks:
      #  - id: prettier
        # files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$

  # ruff for Python formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
      - id: ruff-format
