services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: portfolio-proxy
    container_name: portfolio-proxy
    networks:
      - portfolio-net
    ports:
      - "443:443/tcp"
    volumes:
      - /etc/letsencrypt/:/etc/ssl/letsencrypt/:ro
      - ./nginx/default-nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: portfolio-web
    container_name: portfolio-web
    networks:
      - portfolio-net
    volumes:
      - ./nginx/default-nginx-web.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/www
    restart: unless-stopped

networks:
  portfolio-net:
