services:
    portfolio:
      ports:
        - "3000:3000"
      build:
        dockerfile: Dockerfile
      working_dir: /app
      command: /app/.output/server/index.mjs
      stdin_open: true
      tty: true
      networks:
        - default
