services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: portfolio-proxy
    container_name: portfolio-proxy
    networks:
      - portfolio-net
    ports:
      - "80:80/tcp"
    volumes:
      - ./nginx/default-nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: portfolio-web
    container_name: portfolio-web
    networks:
      - portfolio-net
    volumes:
      - ./nginx/default-nginx-web.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/www

networks:
  portfolio-net: 
