name: myportfolio
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: portfolio-proxy
    ports:
      - name: proxy-port
        target: 80
        published: "80"
        protocol: tcp
        app_protocol: http
        mode: host
    volumes:
      - ./nginx/default-nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro 
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: portfolio-web
    expose:
      - "8080/tcp"
    volumes:
      - ./nginx/default-nginx-web.conf:/etc/nginx/conf.d/default.conf:ro 
      - portfolio-www:/www
volumes:
  portfolio-www:
    driver: local
    driver_opts: 
      type: none 
      o: bind
      device: /home/admin/portfolio
